# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "makufoods" ]
  pull_request:
    branches: [ "makufoods" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: makufoods
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      env:
            GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
            GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
            SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@184.174.33.200 << 'EOF'
          set -e  # Exit on any error
          cd /usr/app/mobile-application/payment_service
          git stash
          git pull origin main  # Use branch explicitly
          go build -o payment-service
          pm2 restart payment-service || pm2 start payment-service --name payment-service
        EOF

    # - name: Test
    #   run: go test -v ./...
